version: '3'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=odoo_password
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    image: odoo-pregodi:latest
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo_password
    volumes:
      - odoo-data:/var/lib/odoo
      - ../user-module:/mnt/extra-addons
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge

volumes:
  postgres-data:
  odoo-data: