apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-pregodi
  labels:
    app: odoo-pregodi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-pregodi
  template:
    metadata:
      labels:
        app: odoo-pregodi
    spec:
      containers:
      - name: odoo
        image: odoo-pregodi:latest
        imagePullPolicy: Never
        command: ["odoo"]
        args: ["-i", "base", "-c", "/etc/odoo/odoo.conf"]
        ports:
        - containerPort: 8069
          name: odoo
        - containerPort: 8072
          name: longpolling
        env:
        - name: HOST
          value: postgres-service
        - name: PORT
          value: "5432"
        - name: USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: odoo
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-config
          mountPath: /etc/odoo
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-data-pvc
      - name: odoo-config
        configMap:
          name: odoo-config