apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  selector:
    app: odoo-pregodi
  ports:
  - name: http
    port: 8069
    targetPort: 8069
    nodePort: 30069  
  - name: longpolling
    port: 8072
    targetPort: 8072
    nodePort: 30072  
  type: NodePort